[package]
name = "ops_server"
version = "0.1.0"
authors = ["jake"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.4"
dns-lookup = "1.0.3"
serde_yaml = "0.8"
serde = "1.0.114"